### ISSUE TITLE
Add more CSS properties

### ISSUE THREAD

**Issue by duezerouno** [bradley/Blotter#14]
I am looking into using more CSS properties like:

```
var text = new Blotter.Text("observation", {
  vertical-align: middle,
  mix-blend-mode: multiply
});
```

Did not find anything in the docs to add custom props. Any plans to add this feature?

**Comment by n0k5** [comment]
@duezerouno you could just add these directly to the canvas element via standard CSS?

**Comment by bradley** [comment]
As @n0k5 suggested, I'd bet your intended results for `mix-blend-mode` and `vertical-align` would be met by just applying those to the canvas element (`scope.domElement`). If you're having trouble placing the text within its canvas element for some reason, I'd suggest playing around with the padding attributes.

**Comment by n0k5** [comment]
I had a play around one possible way of doing this [on this CodePen](https://codepen.io/chrishiam/pen/OQQaNE/). It's simply done by applying the `mix-blend-mode` to the entire canvas element, but I'm sure you could get more creative.

**Comment by bradley** [comment]
Dont think there is much more to add here. Closing for now. Love you.
