### ISSUE TITLE
Blotter has build issues on Firefox Nightly (FF60) & Firefox Developer (FF59)

### ISSUE THREAD

**Issue by bradley** [bradley/Blotter#16]
The bug is a little intermittent and needs some investigating. On the most recent versions of Firefox it seems that if you load into http://blotter.js.org with a fresh cache the page will mostly not load Blotter elements on the first load. A refresh seems to fix it. Additionally if you load up a material page (https://blotter.js.org/#/materials/FliesMaterial) first, with a fresh cache, Blotter seems to work fine and you can navigate to the homepage with everything working as usual.

Please investigate. 

Reference comment on [Designer News](https://www.designernews.co/comments/284124)

**Comment by darrenbarklie** [comment]
Showing the same issue on Windows 58.0.2.

**Comment by bradley** [comment]
Still working on sorting this out, but definitely seems to be an issue around how github pages (http://blotter.js.org is hosted via github pages) is encoding the documentation site's javascript (`br`, or [Brotli](https://en.wikipedia.org/wiki/Brotli)) and how firefox is using it prior to being cached. The problem does not seem to effect the Blotter library itself.

**Comment by bradley** [comment]
This has been fixed. It was an issue with external font faces not being loaded before Blotter attempted to render them. On the site, the logo, nav items, and all Blotter examples use external fonts so this is why it looked like things werent working. 

I don't love the fix (wrapping the Blotter instantiation calls in `document.fonts.ready.then(function () { ... });` but it's just the documentation site and it works.

Bye!
