### ISSUE TITLE
Combine Materials

### ISSUE THREAD

**Issue by n0k5** [bradley/Blotter#21]
Is it possible to combine multiple materials? If so, how?

**Comment by bradley** [comment]
Sorry, it is not possible to combine Blotter materials. You should consider any Blotter material standalone. Depending on your abilities with GLSL, your best bet would be to begin hacking away at GLSL and using whatever code you come up with in a custom `ShaderMaterial`. See here: https://github.com/bradley/Blotter/wiki/Custom-Materials

Hope that helps.
