### ISSUE TITLE
Controls Documentation

### ISSUE THREAD

**Issue by MikeBannon** [bradley/Blotter#23]
Hi,

Was just wondering if there was any documentation for controls on the text element e.g. on the home page being able to determine colour split location dependant on mouse action. I've looked but can't seem to find anything regarding this, sorry if I've missed it. Any help would be appreciated.

Thanks in advance, Mike. #

**Comment by bradley** [comment]
I believe what youre looking for is here:

http://blotter.js.org/#/materials

There is also general documentation for behaviour all materials conform to in the documentation which you can find here:

http://blotter.js.org/#/documentation

How you decide to set material uniforms is left up to you. There is an existing gist for how the homepage effect works which you can see here (whether or not you want to adjust that script to work with the window and not just the text canvas is, again, up to you):

https://gist.github.com/bradley/863aae88496409ed5801ba69e23568c2
