### ISSUE TITLE
Issue with ImageData (Chrome)

### ISSUE THREAD

**Issue by jluengo13** [bradley/Blotter#24]
'ImageData': The input data length is not a multiple of 4.

**Comment by controversial** [comment]
Duplicate of #15

**Comment by bradley** [comment]
Sorry everyone. I merged https://github.com/bradley/Blotter/pull/34 which should fix that. I didnt make the effort to semvar it and for that I am also sorry. If I or some helpful person ever gets around to putting it on NPM we'll have to be more serious about that.
