### ISSUE TITLE
Webpage not showing in Safari / macOS

### ISSUE THREAD

**Issue by daslicht** [bradley/Blotter#25]
https://blotter.js.org is not showing in Safari / macOS.
The console shows:

```
[Error] THREE.WebGLRenderer: Error creating WebGL context.
	ub (blotter-site.min.js:32:112974)
	(anonymous function) (blotter-site.min.js:32:354127)
	Global Code (blotter-site.min.js:32:354235)
[Error] TypeError: null is not an object (evaluating 'a.getExtension')
	get (blotter-site.min.js:32:93895)
	c (blotter-site.min.js:32:98209)
	ub (blotter-site.min.js:32:113069)
	(anonymous function) (blotter-site.min.js:32:354127)
	Global Code (blotter-site.min.js:32:354235)

```

hope that helps somehow

**Comment by sergey-pimenov** [comment]
First of all thank you very much for excellent library. I have same problem with web-site.

What I see in Chrome 66:

![problem](https://user-images.githubusercontent.com/15109701/39958998-e841b81a-5613-11e8-814e-0cfec31c1d2d.png)

Errors in console:

![chrome-66](https://user-images.githubusercontent.com/15109701/39959005-0c19023e-5614-11e8-9925-d24e99403e02.png)

In Firefox 59 I can see all content, but there are such errors in console:

![firefox-59](https://user-images.githubusercontent.com/15109701/39959031-5ab8e620-5614-11e8-97a7-721fded999c3.png)

In Edge 42 does't display any content:

![edge-42](https://user-images.githubusercontent.com/15109701/39959045-88b21164-5614-11e8-84ec-f7ac1017b743.png)

**Comment by bradley** [comment]
@daslicht, @sergey-pimenov  Your problems appear to be different so (months later, Im sorry) Ill offer some advice to each post:

@daslicht It looks like webgl failed to load in your browser. Note how the error itself is coming from Three.js. That's very early in Blotter's lifecycle and likely has nothing to do with Blotter or even ThreeJS but rather something wrong with your browser or system. However, I think the Three.js project is a better place to debug that issue: https://github.com/mrdoob/three.js/issues/4927

@sergey-pimenov The issue with `ImageData` data lengths should now be fixed after the closing of https://github.com/bradley/Blotter/pull/34.
