### ISSUE TITLE
Uncaught TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by simonquasar** [bradley/Blotter#26]
Hello! 

Just by inserting blogger.js into my `<head>` i get 

_Uncaught TypeError: Cannot read property 'extend' of undefined_
`blogger.js @ line 284: _.extend(Blotter.prototype, EventEmitter.prototype);`

Big up for the project anyway!

**Comment by simonquasar** [comment]
solved using blotter.min.js

**Comment by bradley** [comment]
Whoa... That seems wrong. Were you maybe using a custom build that didnt include underscore.js?

If anyone else experiences this, please re-open.
