### ISSUE TITLE
Just text?

### ISSUE THREAD

**Issue by brunnolou** [bradley/Blotter#27]
Is this just for text?
Would love to add this effect to other elements.

**Comment by bradley** [comment]
Yes, Blotter is for anything that can be rendered as text by the browser (you can use emoji). If youre looking to provide similar effects for images, video, or anything else, Blotter is pretty much GLSL over texts, so you should look into learning more about GLSL [here](https://www.shadertoy.com/), [here](https://thebookofshaders.com/), and [here](https://threejs.org/).

:v:
