### ISSUE TITLE
There is no git tags on GitHub repository

### ISSUE THREAD

**Issue by finch185277** [bradley/Blotter#31]
Hi @bradley ,
We are cdnjs team, we're going to host this library.
The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [git tags](https://github.com/bradley/Blotter/tags) so that it can recognize the correct version and automatically update the repo.
Could you please add git tags for the repo?

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#12646

**Comment by bradley** [comment]
Done!
