### ISSUE TITLE
Blotter.LiquidDistortMaterial is not a constructor

### ISSUE THREAD

**Issue by heaversm** [bradley/Blotter#44]
Hi - just copying the example verbatim from the "basics/example2" documentation and getting an error:

`Blotter.LiquidDistortMaterial is not a constructor` at `var material = new Blotter.LiquidDistortMaterial();`

Any idea what's going on? My html just includes a script with the current production version of blotter, and then another script tag to the code that instantiates blotter, plus a valid dom element to insert the text into.

**Comment by sdnyco** [comment]
For anyone else who might have been initially confused following the official tutorial:

Make sure you are also create the file for whatever material you want to use. In case of the tutorial you need the `liquidDistortMaterial.js` which can be found in [this folder](https://github.com/bradley/Blotter/tree/master/build/materials) in the repo.
