### ISSUE TITLE
Responsive text? And help with making Channel Split material rotation and offset follow cursor!! 

### ISSUE THREAD

**Issue by Adamghd** [bradley/Blotter#53]
Title really.

Is there a way to make the text responsive? Would be great if we could use %'s or vw's

Also, I'm having a really hard time getting my blotter to work like it does on the homepage where the elements offset and rotation essentially follows the cursor. Please help!

**Comment by Akohjesse** [comment]
if this helps, i handle responsive text this way

https://github.com/bradley/Blotter/issues/38#issuecomment-1651667737
